/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospitalmanagementsystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Vihanga
 */
public class Login extends javax.swing.JFrame {
    DbOperation dbo=new DbOperation();
     
    
    public Login() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textUsername = new javax.swing.JTextField();
        textPassword = new javax.swing.JPasswordField();
        loginbut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management Sysytem");
        setBackground(new java.awt.Color(51, 153, 0));
        setForeground(new java.awt.Color(102, 153, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Login Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(204, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("User Name");

        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Password");

        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });

        loginbut.setForeground(new java.awt.Color(153, 0, 0));
        loginbut.setText("Login");
        loginbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(loginbut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(loginbut)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPasswordActionPerformed

    private void loginbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbutActionPerformed
        String username=textUsername.getText();
        switch(username.substring(0,3).toLowerCase()){
            
            case "adm":
                boolean loginadmin=dbo.checkUser(textUsername.getText(),textPassword.getText(),username.substring(0,3));
                if(loginadmin){
                    Admin ad=new Admin(textUsername.getText(),textPassword.getText());
                    ad.setLocationRelativeTo(null);
                    ad.setVisible(true);
                    ad.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    textUsername.setText("");
                    textPassword.setText("");
                          }else{
                    JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
                    textUsername.setText("");
                    textPassword.setText("");
                               }break;
                               
            case "doc":
                boolean loginDoc=dbo.checkUser(textUsername.getText(),textPassword.getText(),username.substring(0,3));
                if(loginDoc){
                    Doctor doc=new Doctor(textUsername.getText(),textPassword.getText());
                    doc.setLocationRelativeTo(null);
                    doc.setVisible(true);
                    doc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    textUsername.setText("");
                    textPassword.setText("");
                          }else{
                    JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
                    textUsername.setText("");
                    textPassword.setText("");
                               }
                break;
                
            case "con":
                boolean loginCon=dbo.checkUser(textUsername.getText(),textPassword.getText(),username.substring(0,3));
                if(loginCon){
                    Consultant con=new Consultant(textUsername.getText(),textPassword.getText());
                    con.setLocationRelativeTo(null);
                    con.setVisible(true);
                    con.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    textUsername.setText("");
                    textPassword.setText("");
                          }else{
                    JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
                    textUsername.setText("");
                    textPassword.setText("");
                               }
                break;
                
            case "nur":
                boolean loginNon=dbo.checkUser(textUsername.getText(),textPassword.getText(),username.substring(0,3));
                if(loginNon){
                    Nurse nur=new Nurse();
                    nur.setLocationRelativeTo(null);
                    nur.setVisible(true);
                    nur.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    textUsername.setText("");
                    textPassword.setText("");
                          }else{
                    JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
                    textUsername.setText("");
                    textPassword.setText("");
                               }
                break;
                
            case "Pat":
                boolean loginPat=dbo.checkUser(textUsername.getText(),textPassword.getText(),username.substring(0,3));
                if(loginPat){
                    Patient pat=new Patient();
                    pat.setLocationRelativeTo(null);
                    pat.setVisible(true);
                    pat.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    textUsername.setText("");
                    textPassword.setText("");
                          }else{
                    JOptionPane.showMessageDialog(this, "Incorrect Username or Password");
                    textUsername.setText("");
                    textPassword.setText("");
                               }
                break;
                
            default :
                JOptionPane.showMessageDialog(this, "Invaild Username");
                textUsername.setText("");
                textPassword.setText("");
                
        }
        
        
        
    }//GEN-LAST:event_loginbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbut;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
